blank_issues_enabled: false
contact_links:
  - name: Mekanism Discord
    url: https://discord.gg/nmSjMGc
    about: The best place to receive quick answers to any questions you may have
  - name: Bug Report
    url: https://github.com/mekanism/Mekanism/issues/new?template=general_issue.yml
    about: Redirects you to creating an issue on the main Mekanism issue tracker.